name: myFirstWorkflow

on:
  workflow_dispatch:
  schedule:
    - cron: "38 14 10 * *"
#on: workflow_dispatch
  #schedule:
    #- cron: '0 15 10 * *'
  #push:
    #branches: [ $default-branch ]
  #pull_request:
    #branches: [ $default-branch ]

jobs:
  build:
    #runs-on: ubuntu-latest
    runs-on: [self-hosted, test]

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello from Octo Organization
