name: test_on_pull_request

on:
  pull_request:

jobs:
  build:
    #runs-on: ubuntu-latest
    runs-on: [self-hosted, test]

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo siema to pull request
